// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_base.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMsgIPAddress struct {
	// Types that are valid to be assigned to Ip:
	//	*CMsgIPAddress_V4
	//	*CMsgIPAddress_V6
	Ip                   isCMsgIPAddress_Ip `protobuf_oneof:"ip"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CMsgIPAddress) Reset()         { *m = CMsgIPAddress{} }
func (m *CMsgIPAddress) String() string { return proto.CompactTextString(m) }
func (*CMsgIPAddress) ProtoMessage()    {}
func (*CMsgIPAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{0}
}

func (m *CMsgIPAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgIPAddress.Unmarshal(m, b)
}
func (m *CMsgIPAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgIPAddress.Marshal(b, m, deterministic)
}
func (m *CMsgIPAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgIPAddress.Merge(m, src)
}
func (m *CMsgIPAddress) XXX_Size() int {
	return xxx_messageInfo_CMsgIPAddress.Size(m)
}
func (m *CMsgIPAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgIPAddress.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgIPAddress proto.InternalMessageInfo

type isCMsgIPAddress_Ip interface {
	isCMsgIPAddress_Ip()
}

type CMsgIPAddress_V4 struct {
	V4 uint32 `protobuf:"fixed32,1,opt,name=v4,oneof"`
}

type CMsgIPAddress_V6 struct {
	V6 []byte `protobuf:"bytes,2,opt,name=v6,oneof"`
}

func (*CMsgIPAddress_V4) isCMsgIPAddress_Ip() {}

func (*CMsgIPAddress_V6) isCMsgIPAddress_Ip() {}

func (m *CMsgIPAddress) GetIp() isCMsgIPAddress_Ip {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *CMsgIPAddress) GetV4() uint32 {
	if x, ok := m.GetIp().(*CMsgIPAddress_V4); ok {
		return x.V4
	}
	return 0
}

func (m *CMsgIPAddress) GetV6() []byte {
	if x, ok := m.GetIp().(*CMsgIPAddress_V6); ok {
		return x.V6
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CMsgIPAddress) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CMsgIPAddress_V4)(nil),
		(*CMsgIPAddress_V6)(nil),
	}
}

type CMsgProtoBufHeader struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ClientSessionid      *int32   `protobuf:"varint,2,opt,name=client_sessionid,json=clientSessionid" json:"client_sessionid,omitempty"`
	RoutingAppid         *uint32  `protobuf:"varint,3,opt,name=routing_appid,json=routingAppid" json:"routing_appid,omitempty"`
	JobidSource          *uint64  `protobuf:"fixed64,10,opt,name=jobid_source,json=jobidSource,def=18446744073709551615" json:"jobid_source,omitempty"`
	JobidTarget          *uint64  `protobuf:"fixed64,11,opt,name=jobid_target,json=jobidTarget,def=18446744073709551615" json:"jobid_target,omitempty"`
	TargetJobName        *string  `protobuf:"bytes,12,opt,name=target_job_name,json=targetJobName" json:"target_job_name,omitempty"`
	SeqNum               *int32   `protobuf:"varint,24,opt,name=seq_num,json=seqNum" json:"seq_num,omitempty"`
	Eresult              *int32   `protobuf:"varint,13,opt,name=eresult,def=2" json:"eresult,omitempty"`
	ErrorMessage         *string  `protobuf:"bytes,14,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	AuthAccountFlags     *uint32  `protobuf:"varint,16,opt,name=auth_account_flags,json=authAccountFlags" json:"auth_account_flags,omitempty"`
	TokenSource          *uint32  `protobuf:"varint,22,opt,name=token_source,json=tokenSource" json:"token_source,omitempty"`
	AdminSpoofingUser    *bool    `protobuf:"varint,23,opt,name=admin_spoofing_user,json=adminSpoofingUser" json:"admin_spoofing_user,omitempty"`
	TransportError       *int32   `protobuf:"varint,17,opt,name=transport_error,json=transportError,def=1" json:"transport_error,omitempty"`
	Messageid            *uint64  `protobuf:"varint,18,opt,name=messageid,def=18446744073709551615" json:"messageid,omitempty"`
	PublisherGroupId     *uint32  `protobuf:"varint,19,opt,name=publisher_group_id,json=publisherGroupId" json:"publisher_group_id,omitempty"`
	Sysid                *uint32  `protobuf:"varint,20,opt,name=sysid" json:"sysid,omitempty"`
	TraceTag             *uint64  `protobuf:"varint,21,opt,name=trace_tag,json=traceTag" json:"trace_tag,omitempty"`
	WebapiKeyId          *uint32  `protobuf:"varint,25,opt,name=webapi_key_id,json=webapiKeyId" json:"webapi_key_id,omitempty"`
	IsFromExternalSource *bool    `protobuf:"varint,26,opt,name=is_from_external_source,json=isFromExternalSource" json:"is_from_external_source,omitempty"`
	ForwardToSysid       []uint32 `protobuf:"varint,27,rep,name=forward_to_sysid,json=forwardToSysid" json:"forward_to_sysid,omitempty"`
	CmSysid              *uint32  `protobuf:"varint,28,opt,name=cm_sysid,json=cmSysid" json:"cm_sysid,omitempty"`
	WgToken              *string  `protobuf:"bytes,30,opt,name=wg_token,json=wgToken" json:"wg_token,omitempty"`
	// Types that are valid to be assigned to IpAddr:
	//	*CMsgProtoBufHeader_Ip
	//	*CMsgProtoBufHeader_IpV6
	IpAddr               isCMsgProtoBufHeader_IpAddr `protobuf_oneof:"ip_addr"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CMsgProtoBufHeader) Reset()         { *m = CMsgProtoBufHeader{} }
func (m *CMsgProtoBufHeader) String() string { return proto.CompactTextString(m) }
func (*CMsgProtoBufHeader) ProtoMessage()    {}
func (*CMsgProtoBufHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{1}
}

func (m *CMsgProtoBufHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgProtoBufHeader.Unmarshal(m, b)
}
func (m *CMsgProtoBufHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgProtoBufHeader.Marshal(b, m, deterministic)
}
func (m *CMsgProtoBufHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgProtoBufHeader.Merge(m, src)
}
func (m *CMsgProtoBufHeader) XXX_Size() int {
	return xxx_messageInfo_CMsgProtoBufHeader.Size(m)
}
func (m *CMsgProtoBufHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgProtoBufHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgProtoBufHeader proto.InternalMessageInfo

const Default_CMsgProtoBufHeader_JobidSource uint64 = 18446744073709551615
const Default_CMsgProtoBufHeader_JobidTarget uint64 = 18446744073709551615
const Default_CMsgProtoBufHeader_Eresult int32 = 2
const Default_CMsgProtoBufHeader_TransportError int32 = 1
const Default_CMsgProtoBufHeader_Messageid uint64 = 18446744073709551615

func (m *CMsgProtoBufHeader) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetClientSessionid() int32 {
	if m != nil && m.ClientSessionid != nil {
		return *m.ClientSessionid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetRoutingAppid() uint32 {
	if m != nil && m.RoutingAppid != nil {
		return *m.RoutingAppid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetJobidSource() uint64 {
	if m != nil && m.JobidSource != nil {
		return *m.JobidSource
	}
	return Default_CMsgProtoBufHeader_JobidSource
}

func (m *CMsgProtoBufHeader) GetJobidTarget() uint64 {
	if m != nil && m.JobidTarget != nil {
		return *m.JobidTarget
	}
	return Default_CMsgProtoBufHeader_JobidTarget
}

func (m *CMsgProtoBufHeader) GetTargetJobName() string {
	if m != nil && m.TargetJobName != nil {
		return *m.TargetJobName
	}
	return ""
}

func (m *CMsgProtoBufHeader) GetSeqNum() int32 {
	if m != nil && m.SeqNum != nil {
		return *m.SeqNum
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgProtoBufHeader_Eresult
}

func (m *CMsgProtoBufHeader) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *CMsgProtoBufHeader) GetAuthAccountFlags() uint32 {
	if m != nil && m.AuthAccountFlags != nil {
		return *m.AuthAccountFlags
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetTokenSource() uint32 {
	if m != nil && m.TokenSource != nil {
		return *m.TokenSource
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetAdminSpoofingUser() bool {
	if m != nil && m.AdminSpoofingUser != nil {
		return *m.AdminSpoofingUser
	}
	return false
}

func (m *CMsgProtoBufHeader) GetTransportError() int32 {
	if m != nil && m.TransportError != nil {
		return *m.TransportError
	}
	return Default_CMsgProtoBufHeader_TransportError
}

func (m *CMsgProtoBufHeader) GetMessageid() uint64 {
	if m != nil && m.Messageid != nil {
		return *m.Messageid
	}
	return Default_CMsgProtoBufHeader_Messageid
}

func (m *CMsgProtoBufHeader) GetPublisherGroupId() uint32 {
	if m != nil && m.PublisherGroupId != nil {
		return *m.PublisherGroupId
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetSysid() uint32 {
	if m != nil && m.Sysid != nil {
		return *m.Sysid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetTraceTag() uint64 {
	if m != nil && m.TraceTag != nil {
		return *m.TraceTag
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetWebapiKeyId() uint32 {
	if m != nil && m.WebapiKeyId != nil {
		return *m.WebapiKeyId
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetIsFromExternalSource() bool {
	if m != nil && m.IsFromExternalSource != nil {
		return *m.IsFromExternalSource
	}
	return false
}

func (m *CMsgProtoBufHeader) GetForwardToSysid() []uint32 {
	if m != nil {
		return m.ForwardToSysid
	}
	return nil
}

func (m *CMsgProtoBufHeader) GetCmSysid() uint32 {
	if m != nil && m.CmSysid != nil {
		return *m.CmSysid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetWgToken() string {
	if m != nil && m.WgToken != nil {
		return *m.WgToken
	}
	return ""
}

type isCMsgProtoBufHeader_IpAddr interface {
	isCMsgProtoBufHeader_IpAddr()
}

type CMsgProtoBufHeader_Ip struct {
	Ip uint32 `protobuf:"varint,15,opt,name=ip,oneof"`
}

type CMsgProtoBufHeader_IpV6 struct {
	IpV6 []byte `protobuf:"bytes,29,opt,name=ip_v6,json=ipV6,oneof"`
}

func (*CMsgProtoBufHeader_Ip) isCMsgProtoBufHeader_IpAddr() {}

func (*CMsgProtoBufHeader_IpV6) isCMsgProtoBufHeader_IpAddr() {}

func (m *CMsgProtoBufHeader) GetIpAddr() isCMsgProtoBufHeader_IpAddr {
	if m != nil {
		return m.IpAddr
	}
	return nil
}

func (m *CMsgProtoBufHeader) GetIp() uint32 {
	if x, ok := m.GetIpAddr().(*CMsgProtoBufHeader_Ip); ok {
		return x.Ip
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetIpV6() []byte {
	if x, ok := m.GetIpAddr().(*CMsgProtoBufHeader_IpV6); ok {
		return x.IpV6
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CMsgProtoBufHeader) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CMsgProtoBufHeader_Ip)(nil),
		(*CMsgProtoBufHeader_IpV6)(nil),
	}
}

type CMsgMulti struct {
	SizeUnzipped         *uint32  `protobuf:"varint,1,opt,name=size_unzipped,json=sizeUnzipped" json:"size_unzipped,omitempty"`
	MessageBody          []byte   `protobuf:"bytes,2,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgMulti) Reset()         { *m = CMsgMulti{} }
func (m *CMsgMulti) String() string { return proto.CompactTextString(m) }
func (*CMsgMulti) ProtoMessage()    {}
func (*CMsgMulti) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{2}
}

func (m *CMsgMulti) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgMulti.Unmarshal(m, b)
}
func (m *CMsgMulti) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgMulti.Marshal(b, m, deterministic)
}
func (m *CMsgMulti) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgMulti.Merge(m, src)
}
func (m *CMsgMulti) XXX_Size() int {
	return xxx_messageInfo_CMsgMulti.Size(m)
}
func (m *CMsgMulti) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgMulti.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgMulti proto.InternalMessageInfo

func (m *CMsgMulti) GetSizeUnzipped() uint32 {
	if m != nil && m.SizeUnzipped != nil {
		return *m.SizeUnzipped
	}
	return 0
}

func (m *CMsgMulti) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

type CMsgProtobufWrapped struct {
	MessageBody          []byte   `protobuf:"bytes,1,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgProtobufWrapped) Reset()         { *m = CMsgProtobufWrapped{} }
func (m *CMsgProtobufWrapped) String() string { return proto.CompactTextString(m) }
func (*CMsgProtobufWrapped) ProtoMessage()    {}
func (*CMsgProtobufWrapped) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{3}
}

func (m *CMsgProtobufWrapped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgProtobufWrapped.Unmarshal(m, b)
}
func (m *CMsgProtobufWrapped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgProtobufWrapped.Marshal(b, m, deterministic)
}
func (m *CMsgProtobufWrapped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgProtobufWrapped.Merge(m, src)
}
func (m *CMsgProtobufWrapped) XXX_Size() int {
	return xxx_messageInfo_CMsgProtobufWrapped.Size(m)
}
func (m *CMsgProtobufWrapped) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgProtobufWrapped.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgProtobufWrapped proto.InternalMessageInfo

func (m *CMsgProtobufWrapped) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

type CMsgAuthTicket struct {
	Estate               *uint32  `protobuf:"varint,1,opt,name=estate" json:"estate,omitempty"`
	Eresult              *uint32  `protobuf:"varint,2,opt,name=eresult,def=2" json:"eresult,omitempty"`
	Steamid              *uint64  `protobuf:"fixed64,3,opt,name=steamid" json:"steamid,omitempty"`
	Gameid               *uint64  `protobuf:"fixed64,4,opt,name=gameid" json:"gameid,omitempty"`
	HSteamPipe           *uint32  `protobuf:"varint,5,opt,name=h_steam_pipe,json=hSteamPipe" json:"h_steam_pipe,omitempty"`
	TicketCrc            *uint32  `protobuf:"varint,6,opt,name=ticket_crc,json=ticketCrc" json:"ticket_crc,omitempty"`
	Ticket               []byte   `protobuf:"bytes,7,opt,name=ticket" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgAuthTicket) Reset()         { *m = CMsgAuthTicket{} }
func (m *CMsgAuthTicket) String() string { return proto.CompactTextString(m) }
func (*CMsgAuthTicket) ProtoMessage()    {}
func (*CMsgAuthTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{4}
}

func (m *CMsgAuthTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgAuthTicket.Unmarshal(m, b)
}
func (m *CMsgAuthTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgAuthTicket.Marshal(b, m, deterministic)
}
func (m *CMsgAuthTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgAuthTicket.Merge(m, src)
}
func (m *CMsgAuthTicket) XXX_Size() int {
	return xxx_messageInfo_CMsgAuthTicket.Size(m)
}
func (m *CMsgAuthTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgAuthTicket.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgAuthTicket proto.InternalMessageInfo

const Default_CMsgAuthTicket_Eresult uint32 = 2

func (m *CMsgAuthTicket) GetEstate() uint32 {
	if m != nil && m.Estate != nil {
		return *m.Estate
	}
	return 0
}

func (m *CMsgAuthTicket) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgAuthTicket_Eresult
}

func (m *CMsgAuthTicket) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgAuthTicket) GetGameid() uint64 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *CMsgAuthTicket) GetHSteamPipe() uint32 {
	if m != nil && m.HSteamPipe != nil {
		return *m.HSteamPipe
	}
	return 0
}

func (m *CMsgAuthTicket) GetTicketCrc() uint32 {
	if m != nil && m.TicketCrc != nil {
		return *m.TicketCrc
	}
	return 0
}

func (m *CMsgAuthTicket) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type CCDDBAppDetailCommon struct {
	Appid                 *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Name                  *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Icon                  *string  `protobuf:"bytes,3,opt,name=icon" json:"icon,omitempty"`
	Logo                  *string  `protobuf:"bytes,4,opt,name=logo" json:"logo,omitempty"`
	LogoSmall             *string  `protobuf:"bytes,5,opt,name=logo_small,json=logoSmall" json:"logo_small,omitempty"`
	Tool                  *bool    `protobuf:"varint,6,opt,name=tool" json:"tool,omitempty"`
	Demo                  *bool    `protobuf:"varint,7,opt,name=demo" json:"demo,omitempty"`
	Media                 *bool    `protobuf:"varint,8,opt,name=media" json:"media,omitempty"`
	CommunityVisibleStats *bool    `protobuf:"varint,9,opt,name=community_visible_stats,json=communityVisibleStats" json:"community_visible_stats,omitempty"`
	FriendlyName          *string  `protobuf:"bytes,10,opt,name=friendly_name,json=friendlyName" json:"friendly_name,omitempty"`
	Propagation           *string  `protobuf:"bytes,11,opt,name=propagation" json:"propagation,omitempty"`
	HasAdultContent       *bool    `protobuf:"varint,12,opt,name=has_adult_content,json=hasAdultContent" json:"has_adult_content,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CCDDBAppDetailCommon) Reset()         { *m = CCDDBAppDetailCommon{} }
func (m *CCDDBAppDetailCommon) String() string { return proto.CompactTextString(m) }
func (*CCDDBAppDetailCommon) ProtoMessage()    {}
func (*CCDDBAppDetailCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{5}
}

func (m *CCDDBAppDetailCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCDDBAppDetailCommon.Unmarshal(m, b)
}
func (m *CCDDBAppDetailCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCDDBAppDetailCommon.Marshal(b, m, deterministic)
}
func (m *CCDDBAppDetailCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCDDBAppDetailCommon.Merge(m, src)
}
func (m *CCDDBAppDetailCommon) XXX_Size() int {
	return xxx_messageInfo_CCDDBAppDetailCommon.Size(m)
}
func (m *CCDDBAppDetailCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_CCDDBAppDetailCommon.DiscardUnknown(m)
}

var xxx_messageInfo_CCDDBAppDetailCommon proto.InternalMessageInfo

func (m *CCDDBAppDetailCommon) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CCDDBAppDetailCommon) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetLogo() string {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetLogoSmall() string {
	if m != nil && m.LogoSmall != nil {
		return *m.LogoSmall
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetTool() bool {
	if m != nil && m.Tool != nil {
		return *m.Tool
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetDemo() bool {
	if m != nil && m.Demo != nil {
		return *m.Demo
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetMedia() bool {
	if m != nil && m.Media != nil {
		return *m.Media
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetCommunityVisibleStats() bool {
	if m != nil && m.CommunityVisibleStats != nil {
		return *m.CommunityVisibleStats
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetFriendlyName() string {
	if m != nil && m.FriendlyName != nil {
		return *m.FriendlyName
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetPropagation() string {
	if m != nil && m.Propagation != nil {
		return *m.Propagation
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetHasAdultContent() bool {
	if m != nil && m.HasAdultContent != nil {
		return *m.HasAdultContent
	}
	return false
}

type CMsgAppRights struct {
	EditInfo                 *bool    `protobuf:"varint,1,opt,name=edit_info,json=editInfo" json:"edit_info,omitempty"`
	Publish                  *bool    `protobuf:"varint,2,opt,name=publish" json:"publish,omitempty"`
	ViewErrorData            *bool    `protobuf:"varint,3,opt,name=view_error_data,json=viewErrorData" json:"view_error_data,omitempty"`
	Download                 *bool    `protobuf:"varint,4,opt,name=download" json:"download,omitempty"`
	UploadCdkeys             *bool    `protobuf:"varint,5,opt,name=upload_cdkeys,json=uploadCdkeys" json:"upload_cdkeys,omitempty"`
	GenerateCdkeys           *bool    `protobuf:"varint,6,opt,name=generate_cdkeys,json=generateCdkeys" json:"generate_cdkeys,omitempty"`
	ViewFinancials           *bool    `protobuf:"varint,7,opt,name=view_financials,json=viewFinancials" json:"view_financials,omitempty"`
	ManageCeg                *bool    `protobuf:"varint,8,opt,name=manage_ceg,json=manageCeg" json:"manage_ceg,omitempty"`
	ManageSigning            *bool    `protobuf:"varint,9,opt,name=manage_signing,json=manageSigning" json:"manage_signing,omitempty"`
	ManageCdkeys             *bool    `protobuf:"varint,10,opt,name=manage_cdkeys,json=manageCdkeys" json:"manage_cdkeys,omitempty"`
	EditMarketing            *bool    `protobuf:"varint,11,opt,name=edit_marketing,json=editMarketing" json:"edit_marketing,omitempty"`
	EconomySupport           *bool    `protobuf:"varint,12,opt,name=economy_support,json=economySupport" json:"economy_support,omitempty"`
	EconomySupportSupervisor *bool    `protobuf:"varint,13,opt,name=economy_support_supervisor,json=economySupportSupervisor" json:"economy_support_supervisor,omitempty"`
	ManagePricing            *bool    `protobuf:"varint,14,opt,name=manage_pricing,json=managePricing" json:"manage_pricing,omitempty"`
	BroadcastLive            *bool    `protobuf:"varint,15,opt,name=broadcast_live,json=broadcastLive" json:"broadcast_live,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CMsgAppRights) Reset()         { *m = CMsgAppRights{} }
func (m *CMsgAppRights) String() string { return proto.CompactTextString(m) }
func (*CMsgAppRights) ProtoMessage()    {}
func (*CMsgAppRights) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{6}
}

func (m *CMsgAppRights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgAppRights.Unmarshal(m, b)
}
func (m *CMsgAppRights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgAppRights.Marshal(b, m, deterministic)
}
func (m *CMsgAppRights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgAppRights.Merge(m, src)
}
func (m *CMsgAppRights) XXX_Size() int {
	return xxx_messageInfo_CMsgAppRights.Size(m)
}
func (m *CMsgAppRights) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgAppRights.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgAppRights proto.InternalMessageInfo

func (m *CMsgAppRights) GetEditInfo() bool {
	if m != nil && m.EditInfo != nil {
		return *m.EditInfo
	}
	return false
}

func (m *CMsgAppRights) GetPublish() bool {
	if m != nil && m.Publish != nil {
		return *m.Publish
	}
	return false
}

func (m *CMsgAppRights) GetViewErrorData() bool {
	if m != nil && m.ViewErrorData != nil {
		return *m.ViewErrorData
	}
	return false
}

func (m *CMsgAppRights) GetDownload() bool {
	if m != nil && m.Download != nil {
		return *m.Download
	}
	return false
}

func (m *CMsgAppRights) GetUploadCdkeys() bool {
	if m != nil && m.UploadCdkeys != nil {
		return *m.UploadCdkeys
	}
	return false
}

func (m *CMsgAppRights) GetGenerateCdkeys() bool {
	if m != nil && m.GenerateCdkeys != nil {
		return *m.GenerateCdkeys
	}
	return false
}

func (m *CMsgAppRights) GetViewFinancials() bool {
	if m != nil && m.ViewFinancials != nil {
		return *m.ViewFinancials
	}
	return false
}

func (m *CMsgAppRights) GetManageCeg() bool {
	if m != nil && m.ManageCeg != nil {
		return *m.ManageCeg
	}
	return false
}

func (m *CMsgAppRights) GetManageSigning() bool {
	if m != nil && m.ManageSigning != nil {
		return *m.ManageSigning
	}
	return false
}

func (m *CMsgAppRights) GetManageCdkeys() bool {
	if m != nil && m.ManageCdkeys != nil {
		return *m.ManageCdkeys
	}
	return false
}

func (m *CMsgAppRights) GetEditMarketing() bool {
	if m != nil && m.EditMarketing != nil {
		return *m.EditMarketing
	}
	return false
}

func (m *CMsgAppRights) GetEconomySupport() bool {
	if m != nil && m.EconomySupport != nil {
		return *m.EconomySupport
	}
	return false
}

func (m *CMsgAppRights) GetEconomySupportSupervisor() bool {
	if m != nil && m.EconomySupportSupervisor != nil {
		return *m.EconomySupportSupervisor
	}
	return false
}

func (m *CMsgAppRights) GetManagePricing() bool {
	if m != nil && m.ManagePricing != nil {
		return *m.ManagePricing
	}
	return false
}

func (m *CMsgAppRights) GetBroadcastLive() bool {
	if m != nil && m.BroadcastLive != nil {
		return *m.BroadcastLive
	}
	return false
}

type CCuratorPreferences struct {
	SupportedLanguages   *uint32  `protobuf:"varint,1,opt,name=supported_languages,json=supportedLanguages" json:"supported_languages,omitempty"`
	PlatformWindows      *bool    `protobuf:"varint,2,opt,name=platform_windows,json=platformWindows" json:"platform_windows,omitempty"`
	PlatformMac          *bool    `protobuf:"varint,3,opt,name=platform_mac,json=platformMac" json:"platform_mac,omitempty"`
	PlatformLinux        *bool    `protobuf:"varint,4,opt,name=platform_linux,json=platformLinux" json:"platform_linux,omitempty"`
	VrContent            *bool    `protobuf:"varint,5,opt,name=vr_content,json=vrContent" json:"vr_content,omitempty"`
	AdultContentViolence *bool    `protobuf:"varint,6,opt,name=adult_content_violence,json=adultContentViolence" json:"adult_content_violence,omitempty"`
	AdultContentSex      *bool    `protobuf:"varint,7,opt,name=adult_content_sex,json=adultContentSex" json:"adult_content_sex,omitempty"`
	TimestampUpdated     *uint32  `protobuf:"varint,8,opt,name=timestamp_updated,json=timestampUpdated" json:"timestamp_updated,omitempty"`
	TagidsCurated        []uint32 `protobuf:"varint,9,rep,name=tagids_curated,json=tagidsCurated" json:"tagids_curated,omitempty"`
	TagidsFiltered       []uint32 `protobuf:"varint,10,rep,name=tagids_filtered,json=tagidsFiltered" json:"tagids_filtered,omitempty"`
	WebsiteTitle         *string  `protobuf:"bytes,11,opt,name=website_title,json=websiteTitle" json:"website_title,omitempty"`
	WebsiteUrl           *string  `protobuf:"bytes,12,opt,name=website_url,json=websiteUrl" json:"website_url,omitempty"`
	DiscussionUrl        *string  `protobuf:"bytes,13,opt,name=discussion_url,json=discussionUrl" json:"discussion_url,omitempty"`
	ShowBroadcast        *bool    `protobuf:"varint,14,opt,name=show_broadcast,json=showBroadcast" json:"show_broadcast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCuratorPreferences) Reset()         { *m = CCuratorPreferences{} }
func (m *CCuratorPreferences) String() string { return proto.CompactTextString(m) }
func (*CCuratorPreferences) ProtoMessage()    {}
func (*CCuratorPreferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{7}
}

func (m *CCuratorPreferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCuratorPreferences.Unmarshal(m, b)
}
func (m *CCuratorPreferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCuratorPreferences.Marshal(b, m, deterministic)
}
func (m *CCuratorPreferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCuratorPreferences.Merge(m, src)
}
func (m *CCuratorPreferences) XXX_Size() int {
	return xxx_messageInfo_CCuratorPreferences.Size(m)
}
func (m *CCuratorPreferences) XXX_DiscardUnknown() {
	xxx_messageInfo_CCuratorPreferences.DiscardUnknown(m)
}

var xxx_messageInfo_CCuratorPreferences proto.InternalMessageInfo

func (m *CCuratorPreferences) GetSupportedLanguages() uint32 {
	if m != nil && m.SupportedLanguages != nil {
		return *m.SupportedLanguages
	}
	return 0
}

func (m *CCuratorPreferences) GetPlatformWindows() bool {
	if m != nil && m.PlatformWindows != nil {
		return *m.PlatformWindows
	}
	return false
}

func (m *CCuratorPreferences) GetPlatformMac() bool {
	if m != nil && m.PlatformMac != nil {
		return *m.PlatformMac
	}
	return false
}

func (m *CCuratorPreferences) GetPlatformLinux() bool {
	if m != nil && m.PlatformLinux != nil {
		return *m.PlatformLinux
	}
	return false
}

func (m *CCuratorPreferences) GetVrContent() bool {
	if m != nil && m.VrContent != nil {
		return *m.VrContent
	}
	return false
}

func (m *CCuratorPreferences) GetAdultContentViolence() bool {
	if m != nil && m.AdultContentViolence != nil {
		return *m.AdultContentViolence
	}
	return false
}

func (m *CCuratorPreferences) GetAdultContentSex() bool {
	if m != nil && m.AdultContentSex != nil {
		return *m.AdultContentSex
	}
	return false
}

func (m *CCuratorPreferences) GetTimestampUpdated() uint32 {
	if m != nil && m.TimestampUpdated != nil {
		return *m.TimestampUpdated
	}
	return 0
}

func (m *CCuratorPreferences) GetTagidsCurated() []uint32 {
	if m != nil {
		return m.TagidsCurated
	}
	return nil
}

func (m *CCuratorPreferences) GetTagidsFiltered() []uint32 {
	if m != nil {
		return m.TagidsFiltered
	}
	return nil
}

func (m *CCuratorPreferences) GetWebsiteTitle() string {
	if m != nil && m.WebsiteTitle != nil {
		return *m.WebsiteTitle
	}
	return ""
}

func (m *CCuratorPreferences) GetWebsiteUrl() string {
	if m != nil && m.WebsiteUrl != nil {
		return *m.WebsiteUrl
	}
	return ""
}

func (m *CCuratorPreferences) GetDiscussionUrl() string {
	if m != nil && m.DiscussionUrl != nil {
		return *m.DiscussionUrl
	}
	return ""
}

func (m *CCuratorPreferences) GetShowBroadcast() bool {
	if m != nil && m.ShowBroadcast != nil {
		return *m.ShowBroadcast
	}
	return false
}

type CLocalizationToken struct {
	Language             *uint32  `protobuf:"varint,1,opt,name=language" json:"language,omitempty"`
	LocalizedString      *string  `protobuf:"bytes,2,opt,name=localized_string,json=localizedString" json:"localized_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLocalizationToken) Reset()         { *m = CLocalizationToken{} }
func (m *CLocalizationToken) String() string { return proto.CompactTextString(m) }
func (*CLocalizationToken) ProtoMessage()    {}
func (*CLocalizationToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{8}
}

func (m *CLocalizationToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLocalizationToken.Unmarshal(m, b)
}
func (m *CLocalizationToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLocalizationToken.Marshal(b, m, deterministic)
}
func (m *CLocalizationToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLocalizationToken.Merge(m, src)
}
func (m *CLocalizationToken) XXX_Size() int {
	return xxx_messageInfo_CLocalizationToken.Size(m)
}
func (m *CLocalizationToken) XXX_DiscardUnknown() {
	xxx_messageInfo_CLocalizationToken.DiscardUnknown(m)
}

var xxx_messageInfo_CLocalizationToken proto.InternalMessageInfo

func (m *CLocalizationToken) GetLanguage() uint32 {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return 0
}

func (m *CLocalizationToken) GetLocalizedString() string {
	if m != nil && m.LocalizedString != nil {
		return *m.LocalizedString
	}
	return ""
}

type CClanEventUserNewsTuple struct {
	Clanid               *uint32  `protobuf:"varint,1,opt,name=clanid" json:"clanid,omitempty"`
	EventGid             *uint64  `protobuf:"fixed64,2,opt,name=event_gid,json=eventGid" json:"event_gid,omitempty"`
	AnnouncementGid      *uint64  `protobuf:"fixed64,3,opt,name=announcement_gid,json=announcementGid" json:"announcement_gid,omitempty"`
	RtimeStart           *uint32  `protobuf:"varint,4,opt,name=rtime_start,json=rtimeStart" json:"rtime_start,omitempty"`
	RtimeEnd             *uint32  `protobuf:"varint,5,opt,name=rtime_end,json=rtimeEnd" json:"rtime_end,omitempty"`
	PriorityScore        *uint32  `protobuf:"varint,6,opt,name=priority_score,json=priorityScore" json:"priority_score,omitempty"`
	Type                 *uint32  `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
	ClampRangeSlot       *uint32  `protobuf:"varint,8,opt,name=clamp_range_slot,json=clampRangeSlot" json:"clamp_range_slot,omitempty"`
	Appid                *uint32  `protobuf:"varint,9,opt,name=appid" json:"appid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CClanEventUserNewsTuple) Reset()         { *m = CClanEventUserNewsTuple{} }
func (m *CClanEventUserNewsTuple) String() string { return proto.CompactTextString(m) }
func (*CClanEventUserNewsTuple) ProtoMessage()    {}
func (*CClanEventUserNewsTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{9}
}

func (m *CClanEventUserNewsTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CClanEventUserNewsTuple.Unmarshal(m, b)
}
func (m *CClanEventUserNewsTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CClanEventUserNewsTuple.Marshal(b, m, deterministic)
}
func (m *CClanEventUserNewsTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CClanEventUserNewsTuple.Merge(m, src)
}
func (m *CClanEventUserNewsTuple) XXX_Size() int {
	return xxx_messageInfo_CClanEventUserNewsTuple.Size(m)
}
func (m *CClanEventUserNewsTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_CClanEventUserNewsTuple.DiscardUnknown(m)
}

var xxx_messageInfo_CClanEventUserNewsTuple proto.InternalMessageInfo

func (m *CClanEventUserNewsTuple) GetClanid() uint32 {
	if m != nil && m.Clanid != nil {
		return *m.Clanid
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetEventGid() uint64 {
	if m != nil && m.EventGid != nil {
		return *m.EventGid
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetAnnouncementGid() uint64 {
	if m != nil && m.AnnouncementGid != nil {
		return *m.AnnouncementGid
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetRtimeStart() uint32 {
	if m != nil && m.RtimeStart != nil {
		return *m.RtimeStart
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetRtimeEnd() uint32 {
	if m != nil && m.RtimeEnd != nil {
		return *m.RtimeEnd
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetPriorityScore() uint32 {
	if m != nil && m.PriorityScore != nil {
		return *m.PriorityScore
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetClampRangeSlot() uint32 {
	if m != nil && m.ClampRangeSlot != nil {
		return *m.ClampRangeSlot
	}
	return 0
}

func (m *CClanEventUserNewsTuple) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

type CClanMatchEventByRange struct {
	RtimeBefore          *uint32                    `protobuf:"varint,1,opt,name=rtime_before,json=rtimeBefore" json:"rtime_before,omitempty"`
	RtimeAfter           *uint32                    `protobuf:"varint,2,opt,name=rtime_after,json=rtimeAfter" json:"rtime_after,omitempty"`
	Qualified            *uint32                    `protobuf:"varint,3,opt,name=qualified" json:"qualified,omitempty"`
	Events               []*CClanEventUserNewsTuple `protobuf:"bytes,4,rep,name=events" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CClanMatchEventByRange) Reset()         { *m = CClanMatchEventByRange{} }
func (m *CClanMatchEventByRange) String() string { return proto.CompactTextString(m) }
func (*CClanMatchEventByRange) ProtoMessage()    {}
func (*CClanMatchEventByRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bf300d5da56aa5f, []int{10}
}

func (m *CClanMatchEventByRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CClanMatchEventByRange.Unmarshal(m, b)
}
func (m *CClanMatchEventByRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CClanMatchEventByRange.Marshal(b, m, deterministic)
}
func (m *CClanMatchEventByRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CClanMatchEventByRange.Merge(m, src)
}
func (m *CClanMatchEventByRange) XXX_Size() int {
	return xxx_messageInfo_CClanMatchEventByRange.Size(m)
}
func (m *CClanMatchEventByRange) XXX_DiscardUnknown() {
	xxx_messageInfo_CClanMatchEventByRange.DiscardUnknown(m)
}

var xxx_messageInfo_CClanMatchEventByRange proto.InternalMessageInfo

func (m *CClanMatchEventByRange) GetRtimeBefore() uint32 {
	if m != nil && m.RtimeBefore != nil {
		return *m.RtimeBefore
	}
	return 0
}

func (m *CClanMatchEventByRange) GetRtimeAfter() uint32 {
	if m != nil && m.RtimeAfter != nil {
		return *m.RtimeAfter
	}
	return 0
}

func (m *CClanMatchEventByRange) GetQualified() uint32 {
	if m != nil && m.Qualified != nil {
		return *m.Qualified
	}
	return 0
}

func (m *CClanMatchEventByRange) GetEvents() []*CClanEventUserNewsTuple {
	if m != nil {
		return m.Events
	}
	return nil
}

var E_MsgpoolSoftLimit = &proto.ExtensionDesc{
	ExtendedType:  (*protobuf.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50000,
	Name:          "msgpool_soft_limit",
	Tag:           "varint,50000,opt,name=msgpool_soft_limit,def=32",
	Filename:      "steammessages_base.proto",
}

var E_MsgpoolHardLimit = &proto.ExtensionDesc{
	ExtendedType:  (*protobuf.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50001,
	Name:          "msgpool_hard_limit",
	Tag:           "varint,50001,opt,name=msgpool_hard_limit,def=384",
	Filename:      "steammessages_base.proto",
}

var E_ForcePhpGeneration = &proto.ExtensionDesc{
	ExtendedType:  (*protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50000,
	Name:          "force_php_generation",
	Tag:           "varint,50000,opt,name=force_php_generation,def=0",
	Filename:      "steammessages_base.proto",
}

var E_PhpOutputAlwaysNumber = &proto.ExtensionDesc{
	ExtendedType:  (*protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50020,
	Name:          "php_output_always_number",
	Tag:           "varint,50020,opt,name=php_output_always_number,def=0",
	Filename:      "steammessages_base.proto",
}

func init() {
	proto.RegisterType((*CMsgIPAddress)(nil), "CMsgIPAddress")
	proto.RegisterType((*CMsgProtoBufHeader)(nil), "CMsgProtoBufHeader")
	proto.RegisterType((*CMsgMulti)(nil), "CMsgMulti")
	proto.RegisterType((*CMsgProtobufWrapped)(nil), "CMsgProtobufWrapped")
	proto.RegisterType((*CMsgAuthTicket)(nil), "CMsgAuthTicket")
	proto.RegisterType((*CCDDBAppDetailCommon)(nil), "CCDDBAppDetailCommon")
	proto.RegisterType((*CMsgAppRights)(nil), "CMsgAppRights")
	proto.RegisterType((*CCuratorPreferences)(nil), "CCuratorPreferences")
	proto.RegisterType((*CLocalizationToken)(nil), "CLocalizationToken")
	proto.RegisterType((*CClanEventUserNewsTuple)(nil), "CClanEventUserNewsTuple")
	proto.RegisterType((*CClanMatchEventByRange)(nil), "CClanMatchEventByRange")
	proto.RegisterExtension(E_MsgpoolSoftLimit)
	proto.RegisterExtension(E_MsgpoolHardLimit)
	proto.RegisterExtension(E_ForcePhpGeneration)
	proto.RegisterExtension(E_PhpOutputAlwaysNumber)
}

func init() { proto.RegisterFile("steammessages_base.proto", fileDescriptor_8bf300d5da56aa5f) }

var fileDescriptor_8bf300d5da56aa5f = []byte{
	// 1970 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x97, 0xcd, 0x72, 0x1b, 0xb9,
	0xf1, 0xc0, 0x97, 0xfa, 0x24, 0x21, 0x91, 0x92, 0x61, 0xd9, 0x9e, 0xf5, 0xae, 0xff, 0xe6, 0x9f,
	0xa9, 0x4d, 0x94, 0x4d, 0x4a, 0xfe, 0x92, 0x65, 0xaf, 0x2a, 0x17, 0x89, 0xfe, 0x4c, 0x2c, 0xaf,
	0x6a, 0x28, 0xdb, 0x87, 0x1c, 0x50, 0xe0, 0x4c, 0xcf, 0x10, 0xeb, 0x99, 0x01, 0x0c, 0x60, 0x48,
	0xd3, 0xa7, 0x9c, 0xf2, 0x24, 0x39, 0xe6, 0x94, 0xa7, 0xc8, 0x25, 0x55, 0x9b, 0x77, 0xc8, 0x03,
	0xe4, 0x11, 0x52, 0x0d, 0x60, 0x28, 0x69, 0x3f, 0x2a, 0x39, 0x11, 0xf8, 0x75, 0xa3, 0xd9, 0x0d,
	0x34, 0xba, 0x31, 0x24, 0x32, 0x16, 0x78, 0x59, 0x82, 0x31, 0x3c, 0x07, 0xc3, 0xc6, 0xdc, 0xc0,
	0x9e, 0xd2, 0xd2, 0xca, 0x9b, 0xfd, 0x5c, 0xca, 0xbc, 0x80, 0x3b, 0x6e, 0x36, 0xae, 0xb3, 0x3b,
	0x29, 0x98, 0x44, 0x0b, 0x65, 0xa5, 0xf6, 0x1a, 0x83, 0x6f, 0x48, 0x77, 0x78, 0x62, 0xf2, 0x97,
	0xa7, 0x47, 0x69, 0xaa, 0xc1, 0x18, 0xba, 0x4d, 0x96, 0xa6, 0xfb, 0x51, 0xab, 0xdf, 0xda, 0x5d,
	0x7f, 0xf1, 0x59, 0xbc, 0x34, 0xdd, 0x77, 0xe4, 0x20, 0x5a, 0xea, 0xb7, 0x76, 0x37, 0x1d, 0x39,
	0x38, 0x5e, 0x21, 0x4b, 0x42, 0x0d, 0xfe, 0xb2, 0x4e, 0x28, 0xae, 0x3d, 0x45, 0x43, 0xc7, 0x75,
	0xf6, 0x02, 0x78, 0x0a, 0x9a, 0x46, 0x64, 0xdd, 0xf9, 0x23, 0x52, 0x67, 0x65, 0x2d, 0x6e, 0xa6,
	0xf4, 0xd7, 0x64, 0x3b, 0x29, 0x04, 0x54, 0x96, 0x19, 0x30, 0x46, 0xc8, 0x4a, 0xa4, 0xce, 0xec,
	0x6a, 0xbc, 0xe5, 0xf9, 0xa8, 0xc1, 0xf4, 0x17, 0xa4, 0xab, 0x65, 0x6d, 0x45, 0x95, 0x33, 0xae,
	0x94, 0x48, 0xa3, 0xe5, 0x7e, 0x6b, 0xb7, 0x1b, 0x6f, 0x06, 0x78, 0x84, 0x8c, 0x3e, 0x22, 0x9b,
	0xdf, 0xc9, 0xb1, 0x48, 0x99, 0x91, 0xb5, 0x4e, 0x20, 0x22, 0xf8, 0x77, 0x87, 0x3b, 0xf7, 0x1e,
	0xef, 0xef, 0x1f, 0x3c, 0xda, 0xdf, 0xbf, 0xfb, 0xe8, 0xc1, 0xa3, 0xbb, 0xdf, 0x3c, 0x7c, 0x78,
	0xef, 0xe0, 0xde, 0xc3, 0x78, 0xc3, 0x69, 0x8e, 0x9c, 0xe2, 0xf9, 0x42, 0xcb, 0x75, 0x0e, 0x36,
	0xda, 0xf8, 0xaf, 0x0b, 0xcf, 0x9c, 0x22, 0xfd, 0x25, 0xd9, 0xf2, 0x4b, 0xd8, 0x77, 0x72, 0xcc,
	0x2a, 0x5e, 0x42, 0xb4, 0xd9, 0x6f, 0xed, 0x76, 0xe2, 0xae, 0xc7, 0xbf, 0x97, 0xe3, 0xd7, 0xbc,
	0x04, 0x7a, 0x83, 0xac, 0x1b, 0xf8, 0xc0, 0xaa, 0xba, 0x8c, 0x22, 0x17, 0xe0, 0x9a, 0x81, 0x0f,
	0xaf, 0xeb, 0x92, 0x7e, 0x41, 0xd6, 0x41, 0x83, 0xa9, 0x0b, 0x1b, 0x75, 0x51, 0x70, 0xd8, 0xba,
	0x1f, 0x37, 0x04, 0x83, 0x06, 0xad, 0xa5, 0x66, 0xe1, 0x28, 0xa3, 0x9e, 0xb3, 0xbd, 0xe9, 0xe0,
	0x89, 0x67, 0xf4, 0xb7, 0x84, 0xf2, 0xda, 0x4e, 0x18, 0x4f, 0x12, 0x59, 0x57, 0x96, 0x65, 0x05,
	0xcf, 0x4d, 0xb4, 0xed, 0xb6, 0x67, 0x1b, 0x25, 0x47, 0x5e, 0xf0, 0x0c, 0x39, 0xfd, 0x7f, 0xb2,
	0x69, 0xe5, 0x7b, 0xa8, 0x9a, 0x2d, 0xba, 0xee, 0xf4, 0x36, 0x1c, 0x0b, 0x9b, 0xb1, 0x47, 0xae,
	0xf2, 0xb4, 0x14, 0x15, 0x33, 0x4a, 0xca, 0x0c, 0x77, 0xbc, 0x36, 0xa0, 0xa3, 0x1b, 0xfd, 0xd6,
	0x6e, 0x3b, 0xbe, 0xe2, 0x44, 0xa3, 0x20, 0x79, 0x63, 0x40, 0xd3, 0xaf, 0xc9, 0x96, 0xd5, 0xbc,
	0x32, 0x4a, 0x6a, 0xcb, 0x9c, 0x6b, 0xd1, 0x15, 0x1f, 0xca, 0xbd, 0xb8, 0xb7, 0x90, 0x3c, 0x45,
	0x01, 0xbd, 0x4f, 0x3a, 0x21, 0x16, 0x91, 0x46, 0xb4, 0xdf, 0xda, 0x5d, 0xf9, 0x99, 0x5d, 0x3e,
	0x57, 0xc3, 0x00, 0x55, 0x3d, 0x2e, 0x84, 0x99, 0x80, 0x66, 0xb9, 0x96, 0xb5, 0x62, 0x22, 0x8d,
	0xae, 0xfa, 0x00, 0x17, 0x92, 0xe7, 0x28, 0x78, 0x99, 0xd2, 0x1d, 0xb2, 0x6a, 0xe6, 0x46, 0xa4,
	0xd1, 0x8e, 0x53, 0xf0, 0x13, 0xfa, 0x05, 0xe9, 0x58, 0xcd, 0x13, 0x60, 0x96, 0xe7, 0xd1, 0x35,
	0xfc, 0xdf, 0xb8, 0xed, 0xc0, 0x19, 0xcf, 0xe9, 0x80, 0x74, 0x67, 0x30, 0xe6, 0x4a, 0xb0, 0xf7,
	0x30, 0x47, 0xdb, 0x9f, 0xfb, 0x4d, 0xf1, 0xf0, 0x0f, 0x30, 0x7f, 0x99, 0xd2, 0x87, 0xe4, 0x86,
	0x30, 0x2c, 0xd3, 0xb2, 0x64, 0xf0, 0xd1, 0x82, 0xae, 0x78, 0xd1, 0x6c, 0xe1, 0x4d, 0xb7, 0x31,
	0x3b, 0xc2, 0x3c, 0xd3, 0xb2, 0x7c, 0x1a, 0x84, 0x61, 0x2f, 0x77, 0xc9, 0x76, 0x26, 0xf5, 0x8c,
	0xeb, 0x94, 0x59, 0xc9, 0xbc, 0x63, 0x5f, 0xf4, 0x97, 0x77, 0xbb, 0x71, 0x2f, 0xf0, 0x33, 0x39,
	0x72, 0x1e, 0x7e, 0x4e, 0xda, 0x49, 0x19, 0x34, 0xbe, 0x74, 0xff, 0xbf, 0x9e, 0x94, 0x0b, 0xd1,
	0x2c, 0x67, 0xee, 0x88, 0xa2, 0xff, 0x73, 0x19, 0xb0, 0x3e, 0xcb, 0xcf, 0x70, 0x8a, 0x57, 0x51,
	0xa8, 0x68, 0x0b, 0xf5, 0xf1, 0x2a, 0x0a, 0x45, 0xaf, 0x91, 0x55, 0xa1, 0xd8, 0xf4, 0x20, 0xba,
	0x15, 0xee, 0xe7, 0x8a, 0x50, 0x6f, 0x0f, 0x8e, 0x3b, 0x64, 0x5d, 0x28, 0xc6, 0xd3, 0x54, 0x0f,
	0x46, 0xa4, 0x83, 0xb7, 0xf4, 0xa4, 0x2e, 0xac, 0xc0, 0x14, 0x33, 0xe2, 0x13, 0xb0, 0xba, 0xfa,
	0x24, 0x94, 0x02, 0x7f, 0x45, 0xbb, 0xf1, 0x26, 0xc2, 0x37, 0x81, 0x61, 0xd2, 0x84, 0xe3, 0x60,
	0x63, 0x99, 0xce, 0xfd, 0xd5, 0x8f, 0x37, 0x02, 0x3b, 0x96, 0xe9, 0x7c, 0xf0, 0x98, 0x5c, 0x5d,
	0x5c, 0xfd, 0x71, 0x9d, 0xbd, 0xd3, 0xfc, 0x27, 0x57, 0xb6, 0x7e, 0xbc, 0xf2, 0xfb, 0x16, 0xe9,
	0xe1, 0xd2, 0xa3, 0xda, 0x4e, 0xce, 0x44, 0xf2, 0x1e, 0x2c, 0xbd, 0x4e, 0xd6, 0xc0, 0x58, 0x6e,
	0x21, 0x78, 0x13, 0x66, 0x17, 0x2f, 0x0b, 0xba, 0xd0, 0xbd, 0x74, 0x59, 0x2e, 0x94, 0x99, 0xe5,
	0xcb, 0x65, 0xe6, 0x3a, 0x59, 0xcb, 0x79, 0x89, 0x19, 0xb7, 0xe2, 0x04, 0x61, 0x46, 0xfb, 0x64,
	0x73, 0xc2, 0x9c, 0x12, 0x53, 0x42, 0x41, 0xb4, 0xea, 0xfe, 0x8c, 0x4c, 0x46, 0x88, 0x4e, 0x85,
	0x02, 0x7a, 0x8b, 0x10, 0xeb, 0x5c, 0x62, 0x89, 0x4e, 0xa2, 0x35, 0x27, 0xef, 0x78, 0x32, 0xd4,
	0x09, 0x1a, 0xf6, 0x93, 0x68, 0xdd, 0xc5, 0x15, 0x66, 0x83, 0x7f, 0x2f, 0x91, 0x9d, 0xe1, 0xf0,
	0xc9, 0x93, 0xe3, 0x23, 0xa5, 0x9e, 0x80, 0xe5, 0xa2, 0x18, 0xca, 0xb2, 0x94, 0x15, 0x26, 0xa7,
	0xaf, 0x5e, 0x3e, 0x2e, 0x3f, 0xa1, 0x94, 0xac, 0xb8, 0xca, 0xb1, 0xe4, 0xce, 0xd6, 0x8d, 0x91,
	0x89, 0x44, 0x56, 0x2e, 0x94, 0x4e, 0xec, 0xc6, 0xc8, 0x0a, 0x99, 0x4b, 0x17, 0x45, 0x27, 0x76,
	0x63, 0xf4, 0x10, 0x7f, 0x99, 0x29, 0x79, 0x51, 0xb8, 0x08, 0x3a, 0x71, 0x07, 0xc9, 0x08, 0x01,
	0x2e, 0xb1, 0x52, 0x16, 0xce, 0xf5, 0x76, 0xec, 0xc6, 0xc8, 0x52, 0x28, 0xa5, 0xf3, 0xb9, 0x1d,
	0xbb, 0x31, 0x3a, 0x56, 0x42, 0x2a, 0x78, 0xd4, 0x76, 0xd0, 0x4f, 0xe8, 0x01, 0xb9, 0x91, 0xc8,
	0xb2, 0xac, 0x2b, 0x61, 0xe7, 0x6c, 0x2a, 0x8c, 0x18, 0x17, 0xc0, 0xf0, 0x28, 0x4c, 0xd4, 0x71,
	0x7a, 0xd7, 0x16, 0xe2, 0xb7, 0x5e, 0x3a, 0x42, 0x21, 0x26, 0x55, 0xa6, 0x05, 0x54, 0x69, 0x31,
	0xf7, 0x35, 0x91, 0xf8, 0xba, 0xd5, 0x40, 0x57, 0x12, 0xfb, 0x64, 0x43, 0x69, 0xa9, 0x78, 0xce,
	0xad, 0x90, 0x95, 0x2b, 0xb9, 0x9d, 0xf8, 0x22, 0xa2, 0x5f, 0x93, 0x2b, 0x13, 0x6e, 0x18, 0x4f,
	0xeb, 0xc2, 0xb2, 0x44, 0x56, 0x16, 0x2a, 0xeb, 0xca, 0x6b, 0x3b, 0xde, 0x9a, 0x70, 0x73, 0x84,
	0x7c, 0xe8, 0xf1, 0xe0, 0xef, 0x2b, 0xbe, 0x6f, 0x1d, 0x29, 0x15, 0x8b, 0x7c, 0x62, 0x0d, 0x5e,
	0x79, 0x48, 0x85, 0x65, 0xa2, 0xca, 0xa4, 0xdb, 0xef, 0x76, 0xdc, 0x46, 0xf0, 0xb2, 0xca, 0x24,
	0x26, 0x4b, 0xa8, 0x1c, 0x6e, 0xd7, 0xdb, 0x71, 0x33, 0xc5, 0x8a, 0x3e, 0x15, 0x30, 0xf3, 0x85,
	0x8c, 0xa5, 0xdc, 0x72, 0x77, 0x06, 0xed, 0xb8, 0x8b, 0xd8, 0x55, 0xb1, 0x27, 0xdc, 0x72, 0x7a,
	0x93, 0xb4, 0x53, 0x39, 0xab, 0x0a, 0xc9, 0x7d, 0x5a, 0xb5, 0xe3, 0xc5, 0x1c, 0xe3, 0xaf, 0x15,
	0x8e, 0x58, 0x92, 0xbe, 0x87, 0xb9, 0x71, 0xe7, 0xd2, 0x8e, 0x37, 0x3d, 0x1c, 0x3a, 0x46, 0x7f,
	0x45, 0xb6, 0x72, 0xa8, 0x40, 0x73, 0x0b, 0x8d, 0x9a, 0x3f, 0xa5, 0x5e, 0x83, 0xcf, 0x15, 0x9d,
	0x47, 0x99, 0xa8, 0x78, 0x95, 0x08, 0x5e, 0x98, 0x70, 0x74, 0x3d, 0xc4, 0xcf, 0x16, 0x14, 0x73,
	0xa1, 0xe4, 0x15, 0xde, 0xb5, 0x04, 0xf2, 0x70, 0x92, 0x1d, 0x4f, 0x86, 0x90, 0xd3, 0xaf, 0x48,
	0x2f, 0x88, 0x8d, 0xc8, 0x2b, 0x51, 0xe5, 0xe1, 0x10, 0xbb, 0x9e, 0x8e, 0x3c, 0x44, 0xe7, 0x1b,
	0x2b, 0xde, 0x2b, 0xe2, 0x9d, 0x0f, 0x86, 0xbc, 0x4f, 0x5f, 0x91, 0x9e, 0xdb, 0xdc, 0x92, 0xeb,
	0xf7, 0x80, 0x0d, 0xd8, 0x9d, 0x5f, 0x3b, 0xee, 0x22, 0x3d, 0x69, 0x20, 0xba, 0x0e, 0x89, 0xac,
	0x64, 0x39, 0x67, 0xa6, 0x56, 0xd8, 0x06, 0xc2, 0xf9, 0xf5, 0x02, 0x1e, 0x79, 0x4a, 0x7f, 0x47,
	0x6e, 0xfe, 0x40, 0x11, 0x7f, 0x41, 0x4f, 0x85, 0x91, 0xda, 0x75, 0xc6, 0x76, 0x1c, 0x5d, 0x5e,
	0x33, 0x5a, 0xc8, 0x2f, 0x44, 0xa6, 0xb4, 0x48, 0xd0, 0x9b, 0xde, 0xc5, 0xc8, 0x4e, 0x3d, 0x44,
	0xb5, 0xb1, 0x96, 0x3c, 0x4d, 0xb8, 0xb1, 0xac, 0x10, 0x53, 0x70, 0x85, 0xb3, 0x1d, 0x77, 0x17,
	0xf4, 0x95, 0x98, 0xc2, 0xe0, 0x1f, 0x2b, 0xe4, 0xea, 0x70, 0x58, 0x6b, 0x6e, 0xa5, 0x3e, 0xd5,
	0x90, 0x81, 0x86, 0x2a, 0x01, 0x43, 0xef, 0x90, 0xab, 0xc1, 0x37, 0x48, 0x59, 0xc1, 0xab, 0xbc,
	0xc6, 0xd7, 0x55, 0xb8, 0xca, 0x74, 0x21, 0x7a, 0xd5, 0x48, 0xf0, 0x79, 0xa3, 0x0a, 0x6e, 0x33,
	0xa9, 0x4b, 0x36, 0x13, 0x55, 0x2a, 0x67, 0x26, 0x64, 0xdb, 0x56, 0xc3, 0xdf, 0x79, 0x8c, 0x75,
	0x72, 0xa1, 0x5a, 0xf2, 0x24, 0xa4, 0xdc, 0x46, 0xc3, 0x4e, 0x78, 0x82, 0xde, 0x2f, 0x54, 0x0a,
	0x51, 0xd5, 0x1f, 0x43, 0xda, 0x75, 0x1b, 0xfa, 0x0a, 0x21, 0x26, 0xc1, 0x54, 0x2f, 0x6e, 0x8b,
	0x4f, 0xbc, 0xce, 0x54, 0x87, 0x7b, 0x42, 0xf7, 0xc9, 0xf5, 0x4b, 0xf7, 0x89, 0x4d, 0x85, 0x2c,
	0x30, 0xbe, 0x90, 0x7c, 0x3b, 0xfc, 0xc2, 0xad, 0x7a, 0x1b, 0x64, 0x78, 0x13, 0x2f, 0xaf, 0x32,
	0xf0, 0x31, 0x24, 0xe1, 0xd6, 0xc5, 0x05, 0x23, 0xf8, 0x48, 0x7f, 0x43, 0xae, 0x58, 0x51, 0x62,
	0xc5, 0x2e, 0x15, 0xab, 0x55, 0xca, 0x2d, 0xa4, 0x2e, 0x19, 0xbb, 0xf1, 0xf6, 0x42, 0xf0, 0xc6,
	0x73, 0x0c, 0xca, 0xf2, 0x5c, 0xa4, 0x86, 0x25, 0xb8, 0xe1, 0x90, 0x46, 0x1d, 0xd7, 0x1d, 0xbb,
	0x9e, 0x0e, 0x3d, 0xc4, 0x3c, 0x0a, 0x6a, 0x99, 0x28, 0x2c, 0x68, 0x48, 0x23, 0xe2, 0xbb, 0xa8,
	0xc7, 0xcf, 0x02, 0xc5, 0xe4, 0x9d, 0xc1, 0xd8, 0x08, 0x0b, 0xcc, 0x0a, 0x5b, 0x40, 0x28, 0x2b,
	0x9b, 0x01, 0x9e, 0x21, 0xa3, 0xb7, 0xc9, 0x46, 0xa3, 0x54, 0xeb, 0x22, 0x3c, 0xd8, 0x48, 0x40,
	0x6f, 0x74, 0x81, 0x5e, 0xa5, 0xc2, 0x24, 0xb5, 0x7b, 0x7c, 0x3a, 0x9d, 0xae, 0x7f, 0xd4, 0x9d,
	0xd3, 0xa0, 0x66, 0x26, 0x72, 0xc6, 0x16, 0xe9, 0xd3, 0xa4, 0x1d, 0xd2, 0xe3, 0x06, 0x0e, 0xfe,
	0x48, 0xe8, 0xf0, 0x95, 0x4c, 0x78, 0x21, 0x3e, 0xb9, 0xba, 0xe6, 0x3b, 0xf7, 0x4d, 0xd2, 0x6e,
	0x72, 0x28, 0xa4, 0xd0, 0x62, 0x8e, 0x89, 0x53, 0xf8, 0x05, 0x90, 0x32, 0x63, 0x35, 0x66, 0xb4,
	0x6f, 0x0e, 0x5b, 0x0b, 0x3e, 0x72, 0x78, 0xf0, 0xb7, 0x25, 0x72, 0x63, 0x38, 0x2c, 0x78, 0xf5,
	0x74, 0x0a, 0x95, 0xc5, 0xf7, 0xd8, 0x6b, 0x98, 0x99, 0xb3, 0x5a, 0x15, 0x80, 0xed, 0x29, 0x29,
	0x78, 0xb5, 0x68, 0x37, 0x61, 0xe6, 0x2a, 0x23, 0x6a, 0xb3, 0x3c, 0xbc, 0xb7, 0xd7, 0xe2, 0xb6,
	0x03, 0xcf, 0xfd, 0x9b, 0x9c, 0x57, 0x95, 0xac, 0xab, 0x04, 0xca, 0x46, 0xc7, 0xf7, 0xd3, 0xad,
	0x8b, 0x1c, 0x55, 0x6f, 0x93, 0x0d, 0x8d, 0x27, 0x8a, 0x2d, 0x41, 0x5b, 0x97, 0x8e, 0xdd, 0x98,
	0x38, 0x34, 0x42, 0x82, 0x7f, 0xe4, 0x15, 0xa0, 0x4a, 0x43, 0x77, 0x6d, 0x3b, 0xf0, 0xb4, 0x72,
	0x47, 0xaf, 0xb4, 0x90, 0x1a, 0x7b, 0x8b, 0x49, 0xa4, 0x86, 0xd0, 0x5f, 0xbb, 0x0d, 0x1d, 0x21,
	0x74, 0x1d, 0x6c, 0xae, 0xc0, 0x65, 0x5b, 0x37, 0x76, 0x63, 0x7c, 0x55, 0x25, 0x05, 0xa6, 0x97,
	0xe6, 0x15, 0x96, 0xb3, 0x42, 0xda, 0x90, 0x61, 0x3d, 0xc7, 0x63, 0xc4, 0xa3, 0x42, 0xda, 0xf3,
	0x86, 0xdb, 0xb9, 0xd0, 0x70, 0x07, 0x7f, 0x6d, 0x91, 0xeb, 0x6e, 0xd3, 0x4e, 0xb8, 0x4d, 0x26,
	0x6e, 0xe7, 0x8e, 0xe7, 0x6e, 0x11, 0x5e, 0x44, 0xef, 0xf2, 0x18, 0x32, 0xf4, 0xc9, 0xef, 0x9c,
	0x8f, 0xf3, 0xd8, 0xa1, 0xf3, 0xb0, 0x79, 0x66, 0x41, 0xfb, 0x97, 0x48, 0x08, 0xfb, 0x08, 0x09,
	0xfd, 0x92, 0x74, 0x3e, 0xd4, 0xbc, 0x10, 0x99, 0x80, 0xe6, 0x3b, 0xe5, 0x1c, 0xd0, 0xbb, 0x64,
	0xcd, 0x6d, 0xb6, 0x89, 0x56, 0xfa, 0xcb, 0xbb, 0x1b, 0xf7, 0xa3, 0xbd, 0x9f, 0x39, 0xbf, 0x38,
	0xe8, 0x1d, 0x8e, 0x08, 0x2d, 0x4d, 0xae, 0xa4, 0xc4, 0x27, 0x67, 0x86, 0xa5, 0xab, 0x14, 0x96,
	0xde, 0xde, 0xf3, 0xdf, 0x72, 0x7b, 0xcd, 0xb7, 0xdc, 0x5e, 0xf8, 0x22, 0xf8, 0x56, 0x61, 0x96,
	0x99, 0xe8, 0xfb, 0x3f, 0x2f, 0xbb, 0x67, 0xf8, 0xd2, 0x83, 0xfb, 0xf1, 0x76, 0x30, 0x30, 0x92,
	0x99, 0x7d, 0x85, 0xcb, 0x0f, 0xcf, 0xce, 0x8d, 0x4e, 0xf0, 0x79, 0xfa, 0x3f, 0x1a, 0xfd, 0x67,
	0x30, 0xba, 0xfc, 0xe0, 0xf1, 0xfe, 0xc2, 0xea, 0x0b, 0xae, 0x53, 0x6f, 0xf5, 0x1d, 0xd9, 0xc9,
	0xa4, 0x4e, 0x80, 0xa9, 0x89, 0x62, 0xa1, 0x8f, 0x61, 0x2b, 0xff, 0xf2, 0x47, 0x76, 0x9f, 0x89,
	0xe2, 0x07, 0x9e, 0xb6, 0x0f, 0x57, 0x33, 0x5e, 0x18, 0x88, 0xa9, 0x33, 0x71, 0x3a, 0x51, 0xcf,
	0x17, 0x06, 0x0e, 0x19, 0x89, 0xd0, 0xa4, 0xac, 0xad, 0xaa, 0x2d, 0xe3, 0xc5, 0x8c, 0xcf, 0x0d,
	0x7e, 0x4e, 0x8d, 0x41, 0xd3, 0x5b, 0x3f, 0x61, 0x1c, 0x8a, 0xb4, 0xb1, 0xfe, 0xaf, 0xcb, 0xd6,
	0xaf, 0xa9, 0x89, 0xfa, 0xd6, 0x99, 0x39, 0x72, 0x56, 0x5e, 0x3b, 0x23, 0xc7, 0xab, 0x2f, 0x5a,
	0x7f, 0x6a, 0x7d, 0xf6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x5d, 0x93, 0x57, 0x3b, 0x0f,
	0x00, 0x00,
}
